baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Memes Archive'
theme = 'gokarna'
enableRobotsTXT = true

[params]
  showPostsOnHomePage = "recent"
  metaKeywords = ["memes", "programming", "coding"]
  togglePreviousAndNextButtons = "true"
